# Generated by Django 2.0.13 on 2021-01-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='level',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='board',
            name='expect',
        ),
        migrations.RemoveField(
            model_name='board',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='board',
            name='result',
        ),
        migrations.RemoveField(
            model_name='board',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='board',
            name='team',
        ),
        migrations.RemoveField(
            model_name='board',
            name='time',
        ),
        migrations.AlterField(
            model_name='board',
            name='context',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
