# Generated by Django 3.1.5 on 2021-01-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
